"""replace_role_with_experience

Revision ID: 6f4fdf73cbd5
Revises: bb539b849e3c
Create Date: 2026-06-05 05:33:01.885213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4fdf73cbd5'
down_revision: Union[str, Sequence[str], None] = 'bb539b849e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_matches', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('job_matches', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('job_matches_job_id_candidate_id_key'), 'job_matches', type_='unique')
    op.add_column('job_requests', sa.Column('min_experience_years', sa.Numeric(), nullable=True))
    op.alter_column('job_requests', 'number_of_openings',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('job_requests', 'role_category')
    op.drop_column('job_requests', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_requests', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_requests', sa.Column('role_category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('job_requests', 'number_of_openings',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_column('job_requests', 'min_experience_years')
    op.create_unique_constraint(op.f('job_matches_job_id_candidate_id_key'), 'job_matches', ['job_id', 'candidate_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('job_matches', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('job_matches', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
